# Copyright (c) 2020 The ZMK Contributors
# SPDX-License-Identifier: MIT

# Enables RGB functionality (Uncomment lines below to enable.)
CONFIG_ZMK_RGB_UNDERGLOW=y
CONFIG_WS2812_STRIP=y

#Config to use dedicated thread for UI updates
CONFIG_ZMK_DISPLAY_WORK_QUEUE_DEDICATED=y
#Stack size for the UI thread
CONFIG_ZMK_DISPLAY_DEDICATED_THREAD_STACK_SIZE=2048
#Priority for the UI thread
CONFIG_ZMK_DISPLAY_DEDICATED_THREAD_PRIORITY=5

# Uncomment the following line to enable the OLED Display
CONFIG_ZMK_DISPLAY=y