# Copyright (c) 2020 The ZMK Contributors
# SPDX-License-Identifier: MIT


#Custom Keyboard Name
CONFIG ZMK_KEYBOARD_NAME="Oats' Stainless"

# Enables RGB functionality (Uncomment lines below to enable.)
CONFIG_ZMK_RGB_UNDERGLOW=y
CONFIG_WS2812_STRIP=y
CONFIG_ZMK_RGB_UNDERGLOW_AUTO_OFF_IDLE=y
CONFIG_ZMK_RGB_UNDERGLOW_HUE_START=245
CONFIG_ZMK_RGB_UNDERGLOW_SAT_START=100
CONFIG_ZMK_RGB_UNDERGLOW_BRT_START=15



#Config to use dedicated thread for UI updates
CONFIG_ZMK_DISPLAY_WORK_QUEUE_DEDICATED=y
#Stack size for the UI thread
#CONFIG_ZMK_DISPLAY_DEDICATED_THREAD_STACK_SIZE=2048
#Priority for the UI thread
#CONFIG_ZMK_DISPLAY_DEDICATED_THREAD_PRIORITY=5

# Uncomment the following line to enable the OLED Display
CONFIG_ZMK_DISPLAY=yes