# Copyright (c) 2020 The ZMK Contributors
# SPDX-License-Identifier: MIT
#Experimental BT Connectivity 
CONFIG_ZMK_BLE_EXPERIMENTAL_CONN=y

# Enables RGB functionality (Uncomment lines below to enable.)
CONFIG_ZMK_RGB_UNDERGLOW=y
CONFIG_WS2812_STRIP=y
#config for said strip of rgb 
CONFIG_ZMK_RGB_UNDERGLOW_AUTO_OFF_IDLE=y
CONFIG_ZMK_RGB_UNDERGLOW_HUE_START=245
CONFIG_ZMK_RGB_UNDERGLOW_SAT_START=100
CONFIG_ZMK_RGB_UNDERGLOW_BRT_START=15

#disable backlight (just in case)
CONFIG_ZMK_BACKLIGHT=n

#Config to use dedicated thread for UI updates
CONFIG_ZMK_DISPLAY_WORK_QUEUE_DEDICATED=y
#Stack size for the UI thread (if it must be adjusted)
#CONFIG_ZMK_DISPLAY_DEDICATED_THREAD_STACK_SIZE=2048
#Priority for the UI thread
#CONFIG_ZMK_DISPLAY_DEDICATED_THREAD_PRIORITY=5

#Uncomment the following line to enable the OLED Display
CONFIG_ZMK_DISPLAY=yes
#Locks display update tasks to montior refresh rate
CONFIG_ZMK_DISPLAY_TICK_PERIOD_MS=33
#idles oled on pasts screen
CONFIG_ZMK_DISPLAY_BLANK_ON_IDLE=n
#custom status screen 
CONFIG_ZMK_DISPLAY_STATUS_SCREEN_CUSTOM=y
#show battery %
CONFIG_ZMK_WIDGET_BATTERY_STATUS_SHOW_PERCENTAGE=y
#CONFIG_ZMK_WIDGET_WPM_STATUS=y (seems to cause left side errors)
