manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
     # rotary encoder support based on spare pin
    - name: einboglova
      url-base: https://github.com/einboglova/zmk-helix-ec11
     # support nice_oled and nice_epaper
    - name: mctechnology17
      url-base: https://github.com/mctechnology17
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: v0.3.0
      import: app/west.yml
    - name: zmk-helix-ec11
      remote: einboglova
      revision: main
    - name: zmk-nice-oled
      remote: mctechnology17
      revision: main
      import: app/west.yml
  self:
    path: config
